### ISSUE TITLE
[Feature Request] Option to Download Images

### ISSUE THREAD

**Issue by CharmCityCrab** [mue/mue#142]
**Description**

I would like users to have the option to click on an icon within each new tab page that would allow them to easily download the background photograph being used on said tab in .jpg format for potential use as desktop wallpaper or for viewing on their own computer hard drives.

**Comment by davidjcralph** [comment]
Sure

We'll add it in 5.0 👍

**Comment by CharmCityCrab** [comment]
> Sure
> 
> We'll add it in 5.0 👍

Awesome!  Thanks!

**Comment by davidjcralph** [comment]
This was added a few commits ago, so I'm closing this issue now.

I'll notify you once 5.0 is released on stores, which should hopefully be before the end of the month.
