### ISSUE TITLE
[Feature Request] Search Bar can switch

### ISSUE THREAD

**Issue by cute-angelia** [mue/mue#143]
**Description**

between some custom search engine ( yandex,rarbg... ), hope can switch it by click search engine logo, like this

**Additional context**

![image](https://user-images.githubusercontent.com/26561606/114366692-41791080-9bae-11eb-9ae5-8258b90bd4b9.png)

![image](https://user-images.githubusercontent.com/26561606/114366732-4a69e200-9bae-11eb-8e64-4209d3cc5417.png)

**Comment by davidjcralph** [comment]
Why was this closed? I forgot to reply (sorry!) but this is planned for in the future after 5.0 comes out. There's a card for it on the [Trello](https://trello.com/b/w7zhS7Hi/mue-50).
