### ISSUE TITLE
[Feature Request] Show bookmarkbar

### ISSUE THREAD

**Issue by kkguo** [mue/mue#144]
**Description**
I would like to see bookmarkbar when new tab is opened.

**Comment by eartharoid** [comment]
Are you referring to your browser's built-in bookmarks/favourites bar?

**Comment by kkguo** [comment]
yes.

**Comment by davidjcralph** [comment]
This is already possible in browser settings

Chrome:
![image](https://user-images.githubusercontent.com/14052956/114876083-e20d4180-9df5-11eb-9192-b514f8540cd9.png)

Edge:
![image](https://user-images.githubusercontent.com/14052956/114876171-f81b0200-9df5-11eb-89c6-fbf468d55bd1.png)

Firefox:
![image](https://user-images.githubusercontent.com/14052956/114876230-0832e180-9df6-11eb-951c-d90843438132.png)

**Comment by kkguo** [comment]
The option given by Chrome will show bookmark in all the tabs, I would like to see it only in new tab. The default "new tab" from stock Chrome has this feature.

Haven't tried edge and firfox.
