### ISSUE TITLE
[Bug]Blur setting lost when click on the full screen button

### ISSUE THREAD

**Issue by kkguo** [mue/mue#145]
**Description**
The picture is not blurred when click full screen button.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set Blur to 50%
2. Click on full screen button at the bottom right corner, the background picture will show up in clear.
3. Click again to disable full screen. The picture still clear.

**Expected behaviour**
The picture should apply blur again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Browser: Chrome
 - Browser Version: 89
 - Mue Version: stock version from chrome web app market
 - Resolution: 1920x1080

**Comment by davidjcralph** [comment]
This is intentional behaviour - hiding the widgets and removing the filters to allow you to see the background clearly.

If you wish, I can add an option in 5.0 which will allow you to keep the blur etc enabled at all times.

**Comment by eartharoid** [comment]
> Click again to disable full screen. The picture still clear.

@davidjcralph they mean after returning to the normal view the blur effect is not restored.

**Comment by davidjcralph** [comment]
> > Click again to disable full screen. The picture still clear.
> 
> @davidjcralph they mean after returning to the normal view the blur effect is not restored.

My bad, it is rather late. I think it is fixed if you try on https://demo-dev.muetab.com?

**Comment by davidjcralph** [comment]
This was fixed in the commit above, so I'm closing this issue now.

I'll notify you once 5.0 is released on stores, which should hopefully be before the end of the month.
