### ISSUE TITLE
[Feature Request] Upload multiple images for custom background

### ISSUE THREAD

**Issue by agBAZE** [mue/mue#170]
**Description**
I would like to upload multiple images when using the "custom image" background option.

**Expected behaviour**
It would behave just like other options: the image would change every time a new tab is opened / refreshed.

**Comment by davidjcralph** [comment]
As of 1020787 this has been added (with only one known bug with hot reload that I'll fix soon)

This feature will arrive to the extension stores in the next update (5.4), so I'm closing the issue now.
