### ISSUE TITLE
Multiline messages [Feature Request]

### ISSUE THREAD

**Issue by vroger11** [mue/mue#227]
**Description**
For now, we can only make multiple one line messages. It would be great to be able to break the line (so we can have some kind of bullet points like in a todo list).

**Expected behaviour**
Having multiple messages with one sentence by line in a new tab.

**Design**
I do not thought about a specific design yet.

**Comment by davidcralph** [comment]
Hello,

Thank you for the suggestion. This will be possible as part of the next update, and you'll be able to use ``\n`` in a message to add a line break.
