### ISSUE TITLE
[Bug] AM/PM on Percentage complete type

### ISSUE THREAD

**Issue by aksalsf** [mue/mue#245]
**Description**
AM/PM is still display when I use percentage complete time type

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Time'
3. Change type to Digital and set format to 12 hour
4. Change type to Percentage complete
5. Close Settings

**Expected behaviour**
AM/PM should not display.

**Screenshots**
![image](https://user-images.githubusercontent.com/43602616/156932213-1aca0e02-b339-4d3d-8faa-14594e246b67.png)
![image](https://user-images.githubusercontent.com/43602616/156932231-35304e13-af0c-4696-847f-693fedfd5b53.png)

**Desktop (please complete the following information):**
 - OS: [Pop!_OS]
 - OS Version: [21.10]
 - Browser: [Chrome]
 - Browser Version: [99.0.4844.51]
 - Mue Version: [6.0.4]
 - Resolution: [1360x768]

**Comment by davidcralph** [comment]
Hi,

This will be fixed soon. It seems that it also disappears on refresh? 🤔 

Until a patch is released, please use the following in Advanced -> Custom CSS if it continuously displays:
```css
.ampm {
 display: none;
}
```

Thank you for the report!

**Comment by aksalsf** [comment]
Yes, it dissapears on refresh. Thanks for the solution. Can't wait for the next released, haha.
