### ISSUE TITLE
[Bug]Visual_Layout_Overflow-Branch_7.0

### ISSUE THREAD

**Issue by KaganCanSit** [mue/mue#286]
**Definition**
Visual layout overflow when multiple custom background content is added.

**Reproduce**

1.Go to "Settings/Background/Custom Image/".
2. Click on "Upload"
3. Add more visual content one at a time, one by one.
4. Display the visual overflow.

**Expected behavior**
Keeping the images in the field by means of a scrollable bar.

**Screenshots**
![Overflow in custom images](https://user-images.githubusercontent.com/59123356/178233791-ae06ee81-7fd7-4833-a303-ca8cde2577cc.JPG)

**Desktop (please fill in the information below):**
   - Operating System: [Windows ]
   - OS Version: [10 Pro - 21H2 Version]
   - Browser: [Edge]
   - Browser Version: [Version 103.0.1264.49]
   - Mue Edition: [7 Demo]
   - Resolution: [1920x1080]

**Comment by alexsparkes** [comment]
### Fixed
**Screenshots**
<img width="1200" alt="Screenshot 2022-07-13 at 17 20 04" src="https://user-images.githubusercontent.com/25852280/178782768-b87c2aef-7150-4eaf-a3df-6bbc870a27e4.png">
<img width="1202" alt="Screenshot 2022-07-13 at 17 20 18" src="https://user-images.githubusercontent.com/25852280/178782799-9335b19a-9f7b-4137-b788-cdb0c65349e6.png">

Fixes:
- Fix overflow
- Change design of image cards

**Comment by KaganCanSit** [comment]
I'm glad I could help. Have a good day.
