### ISSUE TITLE
[Bug] Zoom Setting Not Working on 7.0 (and other settings display issues)

### ISSUE THREAD

**Issue by KaganCanSit** [mue/mue#287]
**Definition**
Sequential errors in widget size adjustments.

- Changing only sun icon for weather. The overall size does not change.
- The size of the contact description and buttons do not change in the bid size.
- Navigation buttons do not change size. It's still the same size.

**To produce**
1. Go to "Navigation, Weather or Quote".
2. Change the sizing line.
3. Refresh the page.
4. Visually display unusual sizing or stay still.

**Expected behavior**
- All widget for weather shrink or enlarge relative to the bottom left.
- Reducing contact information and buttons in excerpt with text.
- The scaling of the navigation buttons has been changed.

**Screenshots**
![Weather forecast](https://user-images.githubusercontent.com/59123356/178235539-fe5830d9-bf28-4acf-883e-1073cc3addaa.JPG)
![Weather forecast 0](https://user-images.githubusercontent.com/59123356/178235538-8a7e240d-0136-492d-8202-f7ac990e12bc.JPG)
<hr>

First
![Quote 0](https://user-images.githubusercontent.com/59123356/178235512-8a2e622f-1a45-4322-a717-e9e1e7a2650d.JPG)
![Quote 1](https://user-images.githubusercontent.com/59123356/178235517-37b65c85-c58f-4932-9c45-3fb6976ec0f7.JPG)
Second
![Quote 2](https://user-images.githubusercontent.com/59123356/178235521-1c960c9d-8dba-491f-aa0c-60403f3e94b7.JPG)

<hr>

![navbar 0](https://user-images.githubusercontent.com/59123356/178235907-1aa5feaf-2f89-4794-8342-3c2874c97556.JPG)
![navbar](https://user-images.githubusercontent.com/59123356/178235916-0982a2d2-894a-4d67-aeca-cfad52290c1c.JPG)

**Desktop (please fill in the information below):**
  - Operating System: [Windows ]
  - OS Version: [10 Pro - 21H2 Version]
  - Browser: [Edge]
  - Browser Version: [Version 103.0.1264.49]
  - Mue Edition: [7 Demo]
  - Resolution: [1920x1080]

**Comment by KaganCanSit** [comment]
Hello Again,

I did not recheck the icon scales found here. But today I noticed a few different points while adding the translation. I am adding it below.

See you.

**Screenshots**

Menu is Empty!
![Empty Menu](https://user-images.githubusercontent.com/59123356/206545627-c1031509-91d4-48d9-a0af-020ec107bd76.png)


Map scaling is problematic. It prevents use and information.
![Maps Fault](https://user-images.githubusercontent.com/59123356/206545643-09d90e61-3c8c-4489-9fdd-59e3aed112e4.png)

Object Define Fail
![Object Fault](https://user-images.githubusercontent.com/59123356/206545663-50d63ab6-8f13-4127-ba30-0b68f92999e2.JPG)

**Comment by davidcralph** [comment]
Hi,

I'm sorry for the late response. I'm convinced that these are all fixed or not reproducable now in 7.0, so I'm going to close this issue.

I'll double check the "Zoom" feature you are referring to before I close this though, as that may still be broken.
