### ISSUE TITLE
[Feature Request] Add Option to Remove Potentially Sensitive Content from Settings Packs for the Marketplace Automatically

### ISSUE THREAD

**Issue by RooRay** [mue/mue#320]
**Description**

Add an option to remove potentially sensitive information (such as name, birthday, location for weather) when importing your Mue config to use for Marketplace Settings Packs to not leak said information accidentally.

**Expected behaviour**

Remove/reset settings such as `location`, `birthday`, `greetingName` and others to their default values or blank when the option is selected.

**Design**
<sup>I promise I've used Figma before now 😭</sup>

https://www.figma.com/file/nupK2oBRka6M8PV6Nl3BQv/Mue-Remove-Personal-Info-Idea

![image](https://user-images.githubusercontent.com/86845749/201993849-45966602-d2bf-41f4-9c8c-674a397d64c6.png)

**Comment by davidcralph** [comment]
Fixed in 7.0

**Comment by RooRay** [comment]
luv u big man david
