### ISSUE TITLE
[Todo] [Feature Request] Adding parts that have not yet been added to the translation file.

### ISSUE THREAD

**Issue by KaganCanSit** [mue/mue#330]
**Description**
During the translation process, I saw that some parts were not yet added to the language files. I thought reporting these sections might help you. Good luck with.

**Expected behaviour**
Missing parts can be added to language files at a convenient time for translation and ease of use.

**Screenshots**

*Message Remove Button*
![Message Remove Area](https://user-images.githubusercontent.com/59123356/206542831-cdc21acb-e178-4508-bfaa-52f49a7ae47a.JPG)

*Quick Links Style Menu Title*
![Quick Link Style](https://user-images.githubusercontent.com/59123356/206542839-96e9e40d-f045-4e82-b24e-fb70befd3858.JPG)

*Search Area Marketplace*
![Search Area Marketplace](https://user-images.githubusercontent.com/59123356/206542845-5131ee92-dc2f-469f-879f-0716a0e57491.JPG)

*Main Page 7.0 Avaible Phrase*
![7 0 Avaible](https://user-images.githubusercontent.com/59123356/206542785-b3aa025d-309f-4c9e-a59d-a86c35b8ada4.JPG)

*Marketplace Informations (I'm not sure about this part. It may be pulled from outside. Evaluate.)*
![Marketplace Info Area and Market Items](https://user-images.githubusercontent.com/59123356/206542799-55e14158-f466-4184-a399-cf4607a038a3.JPG)

*Add Setting Area Information*
![Marketplace Stting Package](https://user-images.githubusercontent.com/59123356/206542816-01e8f161-eecf-4139-9894-10e2bafc97d1.JPG)

*Auto Area -> For example, for Turkish language, "Otomatik" should be the last part.*
![Auto](https://user-images.githubusercontent.com/59123356/206552071-c6a3b4da-f2ee-4461-b45e-013a75862ef1.JPG)
![Auto 1](https://user-images.githubusercontent.com/59123356/206552067-65080f51-8531-411e-bed2-93fa359f8414.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10 - Build 19044 - Current
 - Browser: Edge
 - Browser Version: 108.0.1462.42 
 - Mue Version: 7.0 Branch
 - Resolution: [e.g 1920x1080]

**Comment by KaganCanSit** [comment]
I can't change the tags. I thought it would do it automatically with the title change. I made a mistake with the tiredness of the day.
Sory.

**Comment by davidcralph** [comment]
Typical GitHub moment 😅 

Overview news message (which is yet to be fully styled by @alexsparkes) and the marketplace message with link are both external. There is translation support for the news implemented, not sure about marketplace but it will be looked into.

I'll fix the other missing translations soon

**Comment by davidcralph** [comment]
The issues have been fixed as of 41293f075a75e08f961264c7b7bc1ff77f85e826. Settings area seems to be a placeholder accidentally left in the tr translation file, so you can get the newest from en_GB.

**Comment by KaganCanSit** [comment]
Thank you @davidcralph. I updated the translation file based on the en_GB file. But now I'm getting an error while the previous one was successful. I reported it on Discord.
