### ISSUE TITLE
[Bug/Chore] Unsquash the 7.0 commit

### ISSUE THREAD

**Issue by davidcralph** [mue/mue#341]
**Description**
We cannot easily see the changes in the 7.0 on the main branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to commit history
2. Click on Mue 7.0
3. See it all compressssed into one commit

**Expected behaviour**
The original commits should appear

**Comment by davidcralph** [comment]
I have learnt the way of unsquashing. 

For future reference in case someone accidentally does this again:

git reset --hard babc978dcfbad040b7d495744e5f5f2b10821c9 (the commit before the broken one?)
git merge origin/7.0
git add *
git commit -m "yes"
git pull
git push

**Comment by RooRay** [comment]
> I have learnt the way of unsquashing.
> 
> For future reference in case someone accidentally does this again:
> 
> git reset --hard [babc978](https://github.com/mue/mue/commit/babc978dcfbad040b7d495744e5f5f2b10821c99) (the commit before the broken one?) git merge origin/7.0 git add * git commit -m "yes" git pull git push

what's this in english
