### ISSUE TITLE
[Bug] Brightness Adjustments Aren't Reapplied After Maximising and then Minimising

### ISSUE THREAD

**Issue by RooRay** [mue/mue#344]
**Description**

Background brightness adjustments in Mue aren't reapplied if you click on the "Maximise" button once and then click it again until you refresh Mue

**To Reproduce**

Adjust the brightness to anything less than 100%.
Click "Maximise" in the top right
Click it again

**Expected behaviour**

Mue should reapply the adjusted brightness after opening the GUI again from clicking "Maximise" the second time.

**Screenshots**

![Evidence GIF showing the issue](https://user-images.githubusercontent.com/86845749/214963516-649a843a-6c72-4cbf-bb44-c396ddb98a3d.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - Browser: Brave (Chromium)
 - Browser Version: v1.47.171
 - Mue Version: 6.0.6
 - Resolution: 1920x1080

**Additional context**

**Comment by eartharoid** [comment]
Fixed in 7.0.
