### ISSUE TITLE
[Help] Vercel deploy issue

### ISSUE THREAD

**Issue by Metastem** [mue/mue#371]
![QQ截图20230415211255](https://user-images.githubusercontent.com/110768529/232226021-e9862bf2-a589-416a-b2f2-92f3ed6806a1.png)
By the way, can I use cloudflare pages? If so, how to configure? Because my default configs on cloudflare pages not working

**Comment by davidcralph** [comment]
Hi,

Apologies for the late response. I don't think the Vercel issue is related to Mue, but I have fixed the builds on Cloudflare Pages.

Thanks
