### ISSUE TITLE
[Bug] Quick Links Thumbnail mistake

### ISSUE THREAD

**Issue by xXFreeFunXx** [mue/mue#522]
![](https://cdn.discordapp.com/attachments/1106326089569148999/1166178219528044635/quick_links_thumbnail_mistake.gif?ex=65498b1a&is=6537161a&hm=aca0523e6ff3c8c5a6b62cba2b7483762f929694c8915a8f7b4f003e20ec57ec&)

When using a quick link, the thumbnail sometimes turns white.

**Comment by eartharoid** [comment]
😬 weird and very ugly bug

**Comment by davidcralph** [comment]
I'm unable to consistently reproduce this. I'm thinking it's a browser bug to do with the hover styling effects used on the button.

For context, I'm using ``Edge Version 120.0.2210.91 (Official build) (64-bit)`` on Windows 11.

**Comment by Wessel** [comment]
I am also unable to reproduce this issue, closing this for now. Please feel free to re-open this issue if you have any more information concerning this topic.
