### ISSUE TITLE
[Feature Request] Allow setting a specific Unsplash collection by its Id

### ISSUE THREAD

**Issue by luvicsoura** [mue/mue#543]
**Description**
On the background settings, if the selected provider is Unsplash, present a field for inputting a collection Id, to be used by Mue to get the background images.

**Expected behaviour**
After selecting Unsplash as the background provider and setting a collection Id, Mue should only use background images that come from that specific collection.

**Design**
Not sure it'd be needed, but heres an example from Bonjourr.
![image](https://github.com/mue/mue/assets/12973202/6cdfa65a-819f-4279-aa55-176f16ab1313)

**Comment by davidcralph** [comment]
This is a nice idea, and should be fairly easy to implement. @eartharoid am I correct in that the API just needs an extra route on the Unsplash section with a query parameter?

**Comment by eartharoid** [comment]
Yes, easy to add it to the API.
