### ISSUE TITLE
[Bug] Marketplace will not load

### ISSUE THREAD

**Issue by spaceCabbage** [mue/mue#587]
when trying to check out the marketplace it keep saying 
"Looks like your offline"

i am not offline

**To Reproduce**
open a new tab in firefox
open settings 
navigate to marketplace tab
just shows offline error

attached is screenshot of error

**Desktop (please complete the following information):**
desktop
endeavourOs 
kernel 6.6.10-arch-1
firefox v121.0.1
mue version 7.0.0

i tried restarting the tab,
checking my internet connection,
restarted firefoxe 

¯\_(ツ)_/¯

**Comment by spaceCabbage** [comment]
![networkerror](https://github.com/mue/mue/assets/85190787/6ea8c3d2-27c8-45ff-b031-ad0a1e660f7a)

**Comment by spaceCabbage** [comment]
p.s. i just found ur new tab esxtension on reddit and i just started trying it out and im lovin the ui

we need some blur tho

keep it up

**Comment by eartharoid** [comment]
https://marketplace.muetab.com is loading for me. Can you click that link? You should see "Hello World!"

If that works, open a new tab, press F12 and click on the Network tab, then attempt to open the marketplace and see if there's any blocked requests to the marketplace.

![image](https://github.com/mue/mue/assets/20905071/8ce941ea-475f-4b96-8d1b-2bfa40a6e579)

**Comment by spaceCabbage** [comment]
reinstalled and it works now

thanks anyways
