### ISSUE TITLE
[Bug] Invalid regular expression for URLs

### ISSUE THREAD

**Issue by hikariatama** [mue/mue#627]
**Description**
The regular expression provided in the source code (https://github.com/mue/mue/blob/main/src/components/modals/main/settings/sections/utils/utils.js#L23) does not work for some [TLDs](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) (e.g. `.university`, as in my case).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on Quick Links
3. Add a link `https://example.university`

**Expected behaviour**
URL with modern TLD should be allowed to be added.

**Screenshots**
![image](https://github.com/mue/mue/assets/36935426/6a3a27d8-5d6d-406a-92a6-6e8b2eae02d3)
![image](https://github.com/mue/mue/assets/36935426/7934f2ae-7e83-43b3-aa9b-6d2fb86de559)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - Browser: Chrome
 - Browser Version: 121
 - Mue Version: 7.0.1 (latest)
 - Resolution: not relevant

**Additional context**
You should change the regular expression in the place, showed on the second screenshot to comply with the length of modern TLDs.

**Comment by hikariatama** [comment]
Afaik the longest TLD is 18 characters long, so you should update regex to include up to 18 characters

**Comment by Wessel** [comment]
Hey there hikariatama, thanks for your bug report!

I just pushed a change (commit f309967214aad0403e8b7a72392c86ec2abb932a) which fixes this regex string, allowing up to 63 octets in TLDs. This is the maximum according to the RFC 1034 standard (https://www.rfc-editor.org/rfc/rfc1034).

Hope this fixes your issue.
