### ISSUE TITLE
[Bug] Doesn't work on opera

### ISSUE THREAD

**Issue by StuckInThisMind** [mue/mue#881]
### Description

Doesn't work on opera

### Version

7.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidcralph** [comment]
Unfortunately it's not possible to create new tabs for Opera due to them purposely blocking these types of extension.

There may be some workarounds you can try [here](https://www.reddit.com/r/OperaGX/comments/11em482/custom_new_tab_page/), but it's not something we can fix on our side.
