### ISSUE TITLE
[Bug] Minor date thing

### ISSUE THREAD

**Issue by r3a1d3a1** [mue/mue#894]
### Description

When date is in "YMD" and the weekday is shown, it looks ugly. It'd be nicer for weekday to be after day of the month, separated by a comma.

### Version

7.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eartharoid** [comment]
This code is disgusting...

https://github.com/mue/mue/blob/3f3042f354f776685b17cf59166c4553e8a78561/src/features/time/Date.jsx#L68-L80

**Comment by mayur1377** [comment]
Created a fix for there [here](https://github.com/mue/mue/pull/903)! :)

**Comment by davidcralph** [comment]
Closed in #903 🎉
